env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/extensions: 0
  no-console: 0
  react/prop-types: 0
  # react/function-component-definition:
  #   - 2
  #   - namedComponents: 
  #     - function-declaration
  #     - arrow-function
  # react/jsx-filename-extension:
  #   - 1
  #   - extensions:
  #     - .js
  #     - .jsx
